.TH "counter.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
counter.h \- 
.PP
Generic automatic counter data type template class.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::Counter< T >\fP"
.br
.RI "\fIThe counter template is used for generic objects which act as automatic counters. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic automatic counter data type template class. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
