.TH "missing.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
missing.h \- 
.PP
substitute functions which may be missing in target platform libc.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/config.h>\fP
.br
\fC#include <cc++/strchar.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long \fBost::getTicks\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
substitute functions which may be missing in target platform libc. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
