.TH "numbers.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numbers.h \- 
.PP
Numbers and dates manipulation.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/thread.h>\fP
.br
\fC#include <cc++/missing.h>\fP
.br
\fC#include <cc++/strchar.h>\fP
.br
\fC#include <cc++/string.h>\fP
.br
\fC#include <ctime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::Number\fP"
.br
.RI "\fIA number manipulation class. \fP"
.ti -1c
.RI "class \fBost::ZNumber\fP"
.br
.ti -1c
.RI "class \fBost::Date\fP"
.br
.RI "\fIThe \fBDate\fP class uses a julian date representation of the current year, month, and day. \fP"
.ti -1c
.RI "class \fBost::Time\fP"
.br
.RI "\fIThe \fBTime\fP class uses a integer representation of the current time. \fP"
.ti -1c
.RI "class \fBost::Datetime\fP"
.br
.RI "\fIThe \fBDatetime\fP class uses a julian date representation of the current year, month, and day and a integer representation of the current time. \fP"
.ti -1c
.RI "class \fBost::DateNumber\fP"
.br
.RI "\fIA number class that manipulates a string buffer that is also a date. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Numbers and dates manipulation. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
