.TH "objmap.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
objmap.h \- 
.PP
Template for creating hash indexed objects.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/strchar.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::objMap< T, K, S >\fP"
.br
.RI "\fIUsed to create and manage a hash index of objects through a common type. \fP"
.ti -1c
.RI "class \fBost::keyMap< T, S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Template for creating hash indexed objects. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
