ost
NAME
ost -
SYNOPSIS
Classes
class IPV4Validator
Classes derived from IPV4Address would require an specific validator to pass to the IPV4Address constructor.
class IPV4MulticastValidator
Class for the function object that validates multicast addresses.
class IPV4Cidr
The CIDR class is used to support routing tables and validate address policies.
class IPV6Cidr
The CIDR class is used to support routing tables and validate address policies.
class IPV4Address
The network name and address objects are all derived from a common IPV4Address base class.
class IPV4Mask
Internet addresses used specifically as masking addresses (such as '
 255.255.255.0') are held in the IPV4Mask derived object. "
class IPV4Host
This object is used to hold the actual and valid internet address of a specific host machine that will be accessed through a socket.
class IPV4Broadcast
The broadcast address object is used to store the broadcast address for a specific subnet.
class IPV4Multicast
A specialization of IPV4Address that provides address validation for multicast addresses.
class IPV6Validator
Classes derived from IPV6Address would require an specific validator to pass to the IPV6Address constructor.
class IPV6MulticastValidator
Class for the function object that validates multicast addresses.
class IPV6Address
The network name and address objects are all derived from a common IPV6Address base class.
class IPV6Mask
Internet addresses used specifically as masking addresses (such as '
 255.255.255.0') are held in the IPV6Mask derived object. "
class IPV6Host
This object is used to hold the actual and valid internet address of a specific host machine that will be accessed through a socket.
class IPV6Broadcast
The broadcast address object is used to store the broadcast address for a specific subnet.
class IPV6Multicast
A specialization of IPV6Address that provides address validation for multicast addresses.
class HEXdump
Produces a dump of a buffer in a hexdump way with its code Ascii translation and relative buffer address.
class AppLogException
Applog exception, used for memory problems at the moment.
class AppLog
Application logger is a class that implements a logger that can be used by applications to save log file somewhere on the system.
class Buffer
The buffer class represents an IPC service that is built upon a buffer of fixed capacity that can be used to transfer objects between one or more producer and consumer threads.
class FixedBuffer
A buffer class that holds a known capacity of fixed sized objects defined during creation.
class ThreadQueue
Somewhat generic queue processing class to establish a producer consumer queue.
class CommandOption
CommandOption is the base class for all command line options.
class CommandOptionWithArg
Derived class of CommandOption for options that have a value associated with them.
class CommandOptionArg
Class for options with an argument e.g.
class CommandOptionRest
It only makes sense to have a single one of these set and it is exclusive with CommandOptionCollect.
class CommandOptionCollect
It only makes sense to have a single one of these set and it is also exclusive with CommandOptionRest.
class CommandOptionNoArg
CommandOption type for flags.
class CommandOptionParse
This is the CommandOptionParse interface class.
class Counter
The counter template is used for generic objects which act as automatic counters.
class Digest
The digest base class is used for implementing and deriving one way hashing functions.
class ChecksumDigest
A simple checksum digest function.
class CRC16Digest
A crc16 collection/compution hash accumulator class.
class CRC32Digest
A crc32 collection/computation hash accumulator class.
class MD5Digest
A md5 collection/computation accululator class.
class Exception
Mainline exception handler, this is the root for all Common C++ exceptions and assures the ansi C++ exception class hierarchy is both followed and imported into the gnu Common C++ class hierarchy.
class IOException
A sub-hierarchy for all Common C++ I/O related classes.
class ThrException
A sub-hierarchy for thread exceptions.
class SyncException
A sub-hierarchy for all task synchronizion related exceptions.
class InterruptException
class File
class Dir
A low level portable directory class.
class DirTree
A generic class to walk a hierarchical directory structure.
class RandomFile
The purpose of this class is to define a base class for low level random file access that is portable between Win32 and Posix systems.
class ThreadFile
This class defines a database I/O file service that can be shared by multiple threads.
class SharedFile
This class defines a database I/O file service that can be shared by multiple processes.
class MappedFile
Create and map a disk file into memory.
class DSO
The DSO dynamic loader class is used to load object files.
class DirException
class DSOException
class FileException
class MIMEMultipart
A container class for multi-part MIME document objects which can be streamed to a std::ostream destination.
class MIMEMultipartForm
The Multipart form is a MIME multipart document specific for the construction and delivery of form data to a web server through a post method.
class MIMEItemPart
This is used to attach an item part to a MIME multipart document that is being streamed.
class MIMEFormData
This is a document part type for use in submitting multipart form data to a web server.
class MemPager
The memory pager is used to allocate cumulative memory pages for storing object specific 'persistant' data that is presumed to persist during the life of a given derived object.
class StackPager
The StackPager provides a repository to stash and retrieve working data in last-in-first-out order.
class SharedMemPager
The shared mempager uses a mutex to protect key access methods.
class Keydata
Keydata objects are used to load and hold 'configuration' data for a given application.
class MemPagerObject
This class is used to create derived classes which are constructed within a memory pager pool.
class Assoc
This class is used to associate (object) pointers with named strings.
class Runlist
A runlist is used to restrict concurrent exection to a limited set of concurrent sessions, much like a semaphore.
class Runable
A container for objects that can be queued against a runlist.
class NetworkDeviceInfo
Network device information class.
class Number
A number manipulation class.
class ZNumber
class Date
The Date class uses a julian date representation of the current year, month, and day.
class Time
The Time class uses a integer representation of the current time.
class Datetime
The Datetime class uses a julian date representation of the current year, month, and day and a integer representation of the current time.
class DateNumber
A number class that manipulates a string buffer that is also a date.
class objCounter
Generic template class for creating classes which maintain an active count of the number of instances currently in active use.
class RefObject
A reference countable object.
class RefPointer
Pointer to reference counted objects.
class LinkedSingle
Self managed single linked list object chain.
class LinkedDouble
Self managed double linked list object chain.
class MapTable
A map table allows for entities to be mapped (hash index) onto it.
class MapIndex
The MapIndex allows linear access into a MapTable, that otherwise could have its elements being retrieved only by key.
class MapObject
The MapObject is a base class which can be used to make a derived class operate on a MapTable.
class objList
Used to create and manage a single linked list of objects of a common type.
class objMap
Used to create and manage a hash index of objects through a common type.
class keyMap
class objSync
Generic template to create objects of a common base type which share a static mutex so that all instances of the class have a global lock.
struct cistring_char_traits
class PersistException
class TypeManager
This class manages the types for generation of the persistent objects.
class BaseObject
BaseObject.
class Engine
Engine.
class Pointer
Used to create and manage referece counted pointers.
class Process
A class for containing portable process related functions that help create portable code.
class Lockfile
This class is used to create a 'named' lock entity that can be used to control access to a resource between multiple processes.
class Serial
The Serial class is used as the base for all serial I/O services under APE.
class TTYStream
TTY streams are used to represent serial connections that are fully 'streamable' objects using C++ stream classes and friends.
class ttystream
A more natural C++ 'ttystream' class for use by non-threaded applications.
class TTYSession
The TTYSession aggragates a TTYStream and a Common C++ Thread which is assumed to be the execution context that will be used to perform actual I/O operations.
class SerialPort
The serial port is an internal class which is attached to and then serviced by a specified SerialService thread.
class SerialService
The SerialService is a thead service object that is meant to service attached serial ports.
class SerException
class Slog
The slog class is used to stream messages to the system's logging facility (syslogd).
class Socket
The Socket is used as the base for all Internet protocol services under Common C++.
class DCCPSocket
DCCP sockets are used for stream based connected sessions between two sockets.
class UDPSocket
UDP sockets implement the TCP SOCK_DGRAM UDP protocol.
class UDPBroadcast
Representing a UDP socket used for subnet broadcasts, this class provides an alternate binding and setPeer() capability for UDP sockets.
class UDPTransmit
Representing half of a two-way UDP connection, the UDP transmitter can broadcast data to another selected peer host or to an entire subnet.
class UDPReceive
Representing half of a two-way UDP connection, the UDP receiver can receive data from another peer host or subnet.
class UDPDuplex
UDP duplex connections impliment a bi-directional point-to-point UDP session between two peer hosts.
class TCPSocket
TCP sockets are used for stream based connected sessions between two sockets.
class TCPV6Socket
TCPV6 sockets are used for stream based connected sessions between two ipv6 sockets.
class TCPStream
TCP streams are used to represent TCP client connections to a server by TCP protocol servers for accepting client connections.
class TCPSession
The TCP session is used to primarily to represent a client connection that can be managed on a seperate thread.
class SimpleTCPStream
Simple TCP Stream, to be used with Common C++ Library.
class SockException
class SocketPort
The socket port is an internal class which is attached to and then serviced by a specific SocketService 'object'.
class SocketService
The SocketService is a thread pool object that is meant to service attached socket ports.
class SSLStream
class String
This is a generic and portable string class.
class SString
class StringObject
The StringObject class is used to derive subclasses that use the String managed memory pool for all space allocations by overriding new and delete operators.
class Mutex
The Mutex class is used to protect a section of code so that at any given time only a single thread can perform the protected operation.
class MutexLock
The MutexLock class is used to protect a section of code so that at any given time only a single thread can perform the protected operation.
class ThreadLock
The ThreadLock class impliments a thread rwlock for optimal reader performance on systems which have rwlock support, and reverts to a simple mutex for those that do not.
class ReadLock
The ReadLock class is used to protect a section of code through a ThreadLock for 'read' access to the member function.
class WriteLock
The WriteLock class is used to protect a section of code through a ThreadLock for 'write' access to the member function.
class MutexCounter
The Mutex Counter is a counter variable which can safely be incremented or decremented by multiple threads.
class AtomicCounter
The AtomicCounter class offers thread-safe manipulation of an integer counter.
class Conditional
A conditional variable synchcronization object for one to one and one to many signal and control events between processes.
class Semaphore
A semaphore is generally used as a synchronization object between multiple threads or to protect a limited and finite resource such as a memory or thread pool.
class SemaphoreLock
The SemaphoreLock class is used to protect a section of code through a semaphore so that only x instances of the member function may execute concurrently.
class Event
The Event class implements a feature originally found in the WIN32 API; event notification.
class Thread
Every thread of execution in an application is created by instantiating an object of a class derived from the Thread class.
class Cancellation
A class to automatically set the thread cancellation mode of a member function.
class PosixThread
class ThreadKey
This class allows the creation of a thread context unique 'pointer' that can be set and retrieved and can be used to create thread specific data areas for implementing 'thread safe' library routines.
class TimerPort
Timer ports are used to provide synchronized timing events when managed under a 'service thread' such as SocketService.
class SysTime
This class is used to access non-reentrant date and time functions in the standard C library.
class StringTokenizer
Splits delimited string into tokens.
class UnixSocket
Unix domain sockets are used for stream based connected sessions between processes on the same machine.
class UnixStream
Unix streams are used to represent Unix domain client connections to a local server for accepting client connections.
class unixstream
A more natural C++ 'unixstream' class for use by non-threaded applications.
class UnixSession
The Unix domain session is used to primarily to represent a client connection that can be managed on a seperate thread.
class URLStream
A URL processing version of TCPStream.
class XMLStream
This class impliments a basic XML stream parser that can be used to examine an XML resource thru virtual I/O methods.
class XMLRPC
This class impliments a core XMLRPC service without the underlying transports.
class IOZException
class IZStream
class OZStream
Typedefs
typedef unsigned short tpport_t
Transport Protocol Ports.
typedef unsigned long pos_t
typedef size_t ccxx_size_t
typedef std::string_char_traits< char > cstring_char_traits
typedef std::basic_string< char > cstring
typedef std::basic_string< char, cistring_char_traits< char > > cistring
typedef class BaseObject *(* NewBaseObjectFunction )(void)
typedef int signo_t
Functions
__EXPORT std::ostream & operator<< (std::ostream &os, const IPV4Address &ia)
struct in_addr getaddress (const IPV4Address &ia)
__EXPORT std::ostream & operator<< (std::ostream &os, const IPV6Address &ia)
struct in6_addr getaddress (const IPV6Address &ia)
__EXPORT AppLog & debug (AppLog &sl)
Manipulator for debug level.
__EXPORT AppLog & warn (AppLog &sl)
Manipulator for warn level.
__EXPORT AppLog & error (AppLog &sl)
Manipulator for error level.
__EXPORT AppLog & emerg (AppLog &sl)
Manipulator for emerg level.
__EXPORT AppLog & alert (AppLog &sl)
Manipulator for alert level.
__EXPORT AppLog & critical (AppLog &sl)
Manipulator for critical level.
__EXPORT AppLog & notice (AppLog &sl)
Manipulator for notice level.
__EXPORT AppLog & info (AppLog &sl)
Manipulator for info level.
__EXPORT CommandOptionParse * makeCommandOptionParse (int argc, char **argv, const char *comment, CommandOption *options=defaultCommandOptionList)
makeCommandOptionParse will create an implementation of a CommandOptionParse object.
template<typename T > const T & abs (const T &v)
void endKeydata (void)
unsigned long getTicks (void)
char * lsetField (char *target, size_t size, const char *src, const char fill=0)
char * rsetField (char *target, size_t size, const char *src, const char fill=0)
char * setString (char *target, size_t size, const char *src)
char * addString (char *target, size_t size, const char *src)
char * newString (const char *src, size_t size=0)
void delString (char *str)
char * setUpper (char *string, size_t size)
char * setLower (char *string, size_t size)
char * find (const char *cs, char *str, size_t len=0)
char * rfind (const char *cs, char *str, size_t len=0)
char * ifind (const char *cs, char *str, size_t len=0)
char * strip (const char *cs, char *str, size_t len=0)
size_t strchop (const char *cs, char *str, size_t len=0)
size_t strtrim (const char *cs, char *str, size_t len=0)
char * dupString (const char *src, size_t size=0)
struct timespec * getTimeout (struct timespec *spec, timeout_t timeout)
void wait (signo_t signo)
Thread * getThread (void)
Variables
class __EXPORT IPV4Host
class __EXPORT IPV6Host
__EXPORT AppLog alog
alog global log stream definition
__EXPORT CommandOption * defaultCommandOptionList
This defines a linked list head pointer for all the command line options that use the default list.
Slog slog
Typedef Documentation
typedef size_t ost::ccxx_size_t
typedef std::basic_string<char, cistring_char_traits<char> > ost::cistring
typedef std::basic_string<char> ost::cstring
typedef std::string_char_traits<char> ost::cstring_char_traits
typedef class BaseObject*(* ost::NewBaseObjectFunction)(void)
typedef unsigned long ost::pos_t
typedef int ost::signo_t
typedef unsigned short ost::tpport_t
Transport Protocol Ports.
Examples:
SampleSocketPort.cpp, tcp.cpp, tcpservice.cpp, and tcpthread.cpp.
Function Documentation
template<typename T > const T& ost::abs (const T & v) [inline]
char* ost::addString (char * target, size_t size, const char * src)
__EXPORT AppLog& ost::alert (AppLog & sl) [inline]
Manipulator for alert level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelAlert.
__EXPORT AppLog& ost::critical (AppLog & sl) [inline]
Manipulator for critical level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelCritical.
__EXPORT AppLog& ost::debug (AppLog & sl) [inline]
Manipulator for debug level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelDebug.
void ost::delString (char * str)
char* ost::dupString (const char * src, size_t size = 0) [inline]
References newString().
__EXPORT AppLog& ost::emerg (AppLog & sl) [inline]
Manipulator for emerg level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelEmergency.
void ost::endKeydata (void)"This should be used before detaching a deamon, exec(), fork(), etc.
References ost::Keydata::end().
__EXPORT AppLog& ost::error (AppLog & sl) [inline]
Manipulator for error level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelError.
char* ost::find (const char * cs, char * str, size_t len = 0)
struct in6_addr ost::getaddress (const IPV6Address & ia) [read]
struct in_addr ost::getaddress (const IPV4Address & ia) [read]
Thread* ost::getThread (void) [inline]
References ost::Thread::get().
unsigned long ost::getTicks (void)
struct timespec* ost::getTimeout (struct timespec * spec, timeout_t timeout) [read]
char* ost::ifind (const char * cs, char * str, size_t len = 0)
__EXPORT AppLog& ost::info (AppLog & sl) [inline]
Manipulator for info level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelInfo.
char* ost::lsetField (char * target, size_t size, const char * src, const char fill = 0)
__EXPORT CommandOptionParse* ost::makeCommandOptionParse (int argc, char ** argv, const char * comment, CommandOption * options = defaultCommandOptionList)
makeCommandOptionParse will create an implementation of a CommandOptionParse object. This particular implementation is a wrapper around getopt_long(3). That interface unfortunatly does not provide enough information to give the best error messages with malformed input. If the implementation changes there is a good chance that the binary interface will remain the same.
Examples:
cmdlineopt.cpp.
char* ost::newString (const char * src, size_t size = 0)
Referenced by dupString().
__EXPORT AppLog& ost::notice (AppLog & sl) [inline]
Manipulator for notice level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelNotice.
__EXPORT std::ostream& ost::operator<< (std::ostream & os, const IPV6Address & ia)
__EXPORT std::ostream& ost::operator<< (std::ostream & os, const IPV4Address & ia)
char* ost::rfind (const char * cs, char * str, size_t len = 0)
char* ost::rsetField (char * target, size_t size, const char * src, const char fill = 0)
char* ost::setLower (char * string, size_t size)
char* ost::setString (char * target, size_t size, const char * src)
char* ost::setUpper (char * string, size_t size)
size_t ost::strchop (const char * cs, char * str, size_t len = 0)
Referenced by ost::String::chop().
char* ost::strip (const char * cs, char * str, size_t len = 0)
size_t ost::strtrim (const char * cs, char * str, size_t len = 0)
Referenced by ost::String::trim().
void ost::wait (signo_t signo)
Examples:
cmdlineopt.cpp.
__EXPORT AppLog& ost::warn (AppLog & sl) [inline]
Manipulator for warn level. Parameters:
sl application logger stream
Returns:
application logger stream
References ost::Slog::levelWarning.
Variable Documentation
__EXPORT AppLog ost::alog
alog global log stream definition
__EXPORT CommandOption* ost::defaultCommandOptionList
This defines a linked list head pointer for all the command line options that use the default list. It will most likely be used in most cases without being explicitly referenced in application code. It is a default value of various method's parameters.
Examples:
cmdlineopt.cpp.
class __EXPORT ost::IPV4Host
class __EXPORT ost::IPV6Host
Slog ost::slog
Examples:
slogTest.cpp.
Author
Generated automatically by Doxygen for GNU CommonC++ from the source code.