ost::objMap
NAME
ost::objMap -
Used to create and manage a hash index of objects through a common type.
SYNOPSIS
#include <objmap.h>
Static Public Member Functions
static T * getObject (keystring key)
Protected Member Functions
virtual unsigned keyIndex (K k)
unsigned getSize (void)
objMap (const K key)
Protected Attributes
T * objNext
const K objKey
Static Protected Attributes
static T * objIndex [S]
Detailed Description
template<class T, class K, unsigned S> class ost::objMap< T, K, S >
Used to create and manage a hash index of objects through a common type.
The objects can be examined and a specific instance located by a hash key.
Author:
David Sugar <dyfet@gnutelephony.org> hash indexed searchable template chain.
Constructor & Destructor Documentation
template<class T, class K, unsigned S> ost::objMap< T, K, S >::objMap (const K key) [inline, protected]
Member Function Documentation
template<class T , class K , unsigned S> T * ost::objMap< T, K, S >::getObject (keystring key) [inline, static]
References ost::objMap< T, K, S >::keyIndex(), and ost::objMap< T, K, S >::objIndex.
template<class T, class K, unsigned S> unsigned ost::objMap< T, K, S >::getSize (void) [inline, protected]
template<class T, class K, unsigned S> virtual unsigned ost::objMap< T, K, S >::keyIndex (K k) [inline, protected, virtual]
Referenced by ost::objMap< T, K, S >::getObject(), and ost::objMap< T, keystring, S >::objMap().
Member Data Documentation
template<class T, class K, unsigned S> T * ost::objMap< T, K, S >::objIndex () [inline, static, protected]
Referenced by ost::objMap< T, K, S >::getObject(), and ost::objMap< T, keystring, S >::objMap().
template<class T, class K, unsigned S> const K ost::objMap< T, K, S >::objKey [protected]
Referenced by ost::objMap< T, keystring, S >::objMap().
template<class T, class K, unsigned S> T* ost::objMap< T, K, S >::objNext [protected]
Referenced by ost::objMap< T, keystring, S >::objMap().
Author
Generated automatically by Doxygen for GNU CommonC++ from the source code.