.TH "ost::AppLogException" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::AppLogException \- 
.PP
Applog exception, used for memory problems at the moment.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <applog.h>\fP
.PP
Inherits \fBost::Exception\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppLogException\fP (const std::string &what_arg)"
.br
.RI "\fIConstructor. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Applog exception, used for memory problems at the moment. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ost::AppLogException::AppLogException (const std::string & what_arg)\fC [inline]\fP"
.PP
Constructor. \fBParameters:\fP
.RS 4
\fIwhat_arg\fP exception string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
