.TH "ost::Keydata::Keysym" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::Keydata::Keysym \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <misc.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKeysym\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBKeyval\fP * \fBdata\fP"
.br
.ti -1c
.RI "const char ** \fBlist\fP"
.br
.ti -1c
.RI "short \fBcount\fP"
.br
.ti -1c
.RI "char \fBsym\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "short \fBost::Keydata::Keysym::count\fP"
.SS "\fBKeyval\fP* \fBost::Keydata::Keysym::data\fP"
.SS "const char** \fBost::Keydata::Keysym::list\fP"
.SS "\fBKeysym\fP* \fBost::Keydata::Keysym::next\fP"
.SS "char \fBost::Keydata::Keysym::sym\fP[1]"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
