.TH "ost::MIMEMultipartForm" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::MIMEMultipartForm \- 
.PP
The Multipart form is a MIME multipart document specific for the construction and delivery of form data to a web server through a post method.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mime.h>\fP
.PP
Inherits \fBost::MIMEMultipart\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMIMEMultipartForm\fP ()"
.br
.RI "\fIConstruct a form result. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~MIMEMultipartForm\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Multipart form is a MIME multipart document specific for the construction and delivery of form data to a web server through a post method. 

\fBAuthor:\fP
.RS 4
David Sugar <dyfet@ostel.com> deliver form results as multipart document. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ost::MIMEMultipartForm::~MIMEMultipartForm ()\fC [protected, virtual]\fP"
.SS "ost::MIMEMultipartForm::MIMEMultipartForm ()"
.PP
Construct a form result. This is a \fBMIMEMultipart\fP of type multipart/form-data. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
