.TH "ost::keyMap" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::keyMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objmap.h>\fP
.PP
Inherits \fBobjMap< T, keystring, S >\fP.

.SS "template<class T, unsigned S> class ost::keyMap< T, S >"


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
