.TH "ost::File::_fcb" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::File::_fcb \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_fcb\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBaddress\fP"
.br
.ti -1c
.RI "\fBccxx_size_t\fP \fBlen\fP"
.br
.ti -1c
.RI "off_t \fBpos\fP"
.br
.ti -1c
.RI "bool \fBlocked\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* \fBost::File::_fcb::address\fP"
.SS "\fBccxx_size_t\fP \fBost::File::_fcb::len\fP"
.SS "bool \fBost::File::_fcb::locked\fP"
.SS "struct \fB_fcb\fP* \fBost::File::_fcb::next\fP\fC [read]\fP"
.SS "off_t \fBost::File::_fcb::pos\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
