ost::AppLog::Ident
NAME
ost::AppLog::Ident -
Ident class that represents module name.
SYNOPSIS
#include <applog.h>
Public Member Functions
Ident ()
Constructor.
~Ident ()
Desctructor.
Ident (Ident &id)
Copy constructor.
Ident (const char *str)
const char* constructor, provided for convenience.
std::string & str ()
std::string cast.
Ident & operator= (std::string &st)
Assignment operator (string).
Ident & operator= (const char str[])
Assignment operator (const char[]), provided for convenience.
const char * c_str ()
const char* cast provided for conveneince.
Detailed Description
Ident class that represents module name.
Constructor & Destructor Documentation
ost::AppLog::Ident::Ident () [inline]
Constructor.
ost::AppLog::Ident::~Ident () [inline]
Desctructor.
ost::AppLog::Ident::Ident (Ident & id) [inline]
Copy constructor.
ost::AppLog::Ident::Ident (const char * str) [inline]
const char* constructor, provided for convenience.
Member Function Documentation
const char* ost::AppLog::Ident::c_str () [inline]
const char* cast provided for conveneince.
Referenced by ost::AppLog::operator()(), and ost::AppLog::operator<<().
Ident& ost::AppLog::Ident::operator= (const char str[]) [inline]
Assignment operator (const char[]), provided for convenience.
Ident& ost::AppLog::Ident::operator= (std::string & st) [inline]
Assignment operator (string).
std::string& ost::AppLog::Ident::str () [inline]
std::string cast.
Author
Generated automatically by Doxygen for GNU CommonC++ from the source code.