.TH "string.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string.h \- 
.PP
Common C++ generic string class.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/missing.h>\fP
.br
\fC#include <cc++/strchar.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::String\fP"
.br
.RI "\fIThis is a generic and portable string class. \fP"
.ti -1c
.RI "class \fBost::SString\fP"
.br
.ti -1c
.RI "class \fBost::StringObject\fP"
.br
.RI "\fIThe \fBStringObject\fP class is used to derive subclasses that use the \fBString\fP managed memory pool for all space allocations by overriding new and delete operators. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common C++ generic string class. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
