.TH "template.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
template.h \- 
.PP
GNU Common C++ template subsystem.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/config.h>\fP
.br
\fC#include <cc++/objcount.h>\fP
.br
\fC#include <cc++/objlink.h>\fP
.br
\fC#include <cc++/objmap.h>\fP
.br
\fC#include <cc++/objsync.h>\fP
.br
\fC#include <cc++/oststring.h>\fP
.br
\fC#include <cc++/functions.h>\fP
.br
\fC#include <cc++/pointer.h>\fP
.br
\fC#include <cc++/counter.h>\fP
.br

.SH "Detailed Description"
.PP 
GNU Common C++ template subsystem. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
