.TH "todo" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBClass \fBost::Conditional\fP \fP" 1c
implement in win32 
.PP
.PP
 
.IP "\fBMember \fBost::RandomFile::setCompletion\fP(Complete mode) \fP" 1c
implement in win32 
.PP
.PP
 
.IP "\fBMember \fBost::Thread::cancelManual\fP \fP" 1c
implement 
.PP
.PP
 
.IP "\fBMember \fBost::Thread::Thread\fP(const Thread &th) \fP" 1c
implement in win32 
.PP
.PP
 
.IP "\fBMember \fBost::UDPSocket::getInterfaceIndex\fP(const char *ethX, int &InterfaceIndex) \fP" 1c
Win32 and ipv6 specific implementation. 
.PP
.PP
 
.IP "\fBMember \fBost::UDPSocket::join\fP(const IPV4Multicast &ia, int InterfaceIndex) \fP" 1c
Win32 and ipv6 specific implementation. 
.PP

