.TH "tokenizer.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tokenizer.h \- 
.PP
string tokenizer.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/missing.h>\fP
.br
\fC#include <cc++/thread.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::StringTokenizer\fP"
.br
.RI "\fISplits delimited string into tokens. \fP"
.ti -1c
.RI "class \fBost::StringTokenizer::NoSuchElementException\fP"
.br
.RI "\fI\fBException\fP thrown, if someone tried to read beyond the end of the tokens. \fP"
.ti -1c
.RI "class \fBost::StringTokenizer::iterator\fP"
.br
.RI "\fIThe input forward \fBiterator\fP for tokens. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
string tokenizer. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
