.TH "xml.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xml.h \- 
.PP
XML streams abstraction and RPC services.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/missing.h>\fP
.br
\fC#include <cc++/thread.h>\fP
.br
\fC#include <cc++/slog.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::XMLStream\fP"
.br
.RI "\fIThis class impliments a basic XML stream parser that can be used to examine an XML resource thru virtual I/O methods. \fP"
.ti -1c
.RI "class \fBost::XMLRPC\fP"
.br
.RI "\fIThis class impliments a core \fBXMLRPC\fP service without the underlying transports. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
XML streams abstraction and RPC services. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
