/* engine/private.h.  Generated by configure.  */
/* engine/private.h.in.  Generated from configure.ac by autoheader.  */

/* bayonne files */
#define BAYONNE_FILES "/usr/local/share/bayonne"

/* bin files */
#define BIN_FILES "/usr/local/bin"

/* config files */
#define CONFIG_FILES "/etc/bayonne"

/* new option */
/* #undef EXOSIP2_OPTION_SEND_101 */

/* some distros do not pre-build openh323 with gsm or speex */
/* #undef H323_CODECS_DISABLED */

/* we have SENDING_COMPLETE in ALERT_REQ */
/* #undef HAVE_ALERT_SENDING_COMPLETE */

/* has capi 2.0 support */
/* #undef HAVE_CAPI20_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* have fox toolkit for gui */
/* #undef HAVE_FOX */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* libexec enabled */
#define HAVE_LIBEXEC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <stropts.h> header file. */
/* #undef HAVE_STROPTS_H */

/* Define to 1 if you have the <sys/mount.h> header file. */
#define HAVE_SYS_MOUNT_H 1

/* Define to 1 if you have the <sys/statvfs.h> header file. */
#define HAVE_SYS_STATVFS_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/vfs.h> header file. */
#define HAVE_SYS_VFS_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* java binary */
#define JAVA_PROGRAM "/cygdrive/c/Windows/system32/java"

/* libdir path */
#define LIBDIR_FILES "/usr/local/lib/bayonne-2.3"

/* libexec path */
#define LIBEXEC_FILES "/usr/local/share/bayonne/libexec"

/* libexec runner */
#define LIBEXEC_PROGRAM "/usr/local/lib/bayonne-2.3/libexec.bin"

/* log files */
#define LOG_FILES "/var/log/bayonne"

/* macro files */
#define MACRO_FILES "/usr/local/share/bayonne/macros"

/* define module path */
#define MODULE_LIBPATH "/usr/local/lib/bayonne-2.3"

/* define pointer mode */
/* #undef OSIP2_LIST_PTR */

/* Name of package */
#define PACKAGE "bayonne2"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* perl binary */
#define PERL_PROGRAM "/usr/bin/perl"

/* php binary */
#define PHP_PROGRAM "/usr/local/bin/php"

/* ilrun for pnet */
#define PNET_PROGRAM "/usr/local/bin/ilrun"

/* prompt files */
#define PROMPT_FILES "/usr/local/share/phrasebook"

/* python binary */
#define PYTHON_PROGRAM "/usr/bin/python"

/* run files */
#define RUN_FILES "/var/run/bayonne"

/* script files */
#define SCRIPT_FILES "/usr/local/share/bayonne/scripts"

/* shared files */
#define SHARED_FILES "/usr/local/share/bayonne"

/* source files */
#define SOURCE_FILES "/home/WILSON/bayonne/bayonne2-2.3.2"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* var files */
#define VAR_FILES "/var/lib/bayonne"

/* Version number of package */
#define VERSION "2.3.2"

/* zeroconf avahi client */
/* #undef ZEROCONF_AVAHI */
