.TH "digest.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
digest.h \- 
.PP
Digest algorithms: checksum, CRC and MD5.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/missing.h>\fP
.br
\fC#include <cc++/thread.h>\fP
.br
\fC#include <cc++/exception.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::Digest\fP"
.br
.RI "\fIThe digest base class is used for implementing and deriving one way hashing functions. \fP"
.ti -1c
.RI "class \fBost::ChecksumDigest\fP"
.br
.RI "\fIA simple checksum digest function. \fP"
.ti -1c
.RI "class \fBost::CRC16Digest\fP"
.br
.RI "\fIA crc16 collection/compution hash accumulator class. \fP"
.ti -1c
.RI "class \fBost::CRC32Digest\fP"
.br
.RI "\fIA crc32 collection/computation hash accumulator class. \fP"
.ti -1c
.RI "class \fBost::MD5Digest\fP"
.br
.RI "\fIA md5 collection/computation accululator class. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Digest algorithms: checksum, CRC and MD5. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
