.TH "functions.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functions.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > const T & \fBost::abs\fP (const T &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
