.TH "objlink.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
objlink.h \- 
.PP
Template for creating linked list of objects with lookup.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::objList< T, K >\fP"
.br
.RI "\fIUsed to create and manage a single linked list of objects of a common type. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Template for creating linked list of objects with lookup. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
