.TH "ost::Keydata::Define" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::Keydata::Define \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <misc.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBkeyword\fP"
.br
.ti -1c
.RI "const char * \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* \fBost::Keydata::Define::keyword\fP"
.SS "const char* \fBost::Keydata::Define::value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
