.TH "ost::Keydata::Keyval" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::Keydata::Keyval \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <misc.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKeyval\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBval\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBKeyval\fP* \fBost::Keydata::Keyval::next\fP"
.SS "char \fBost::Keydata::Keyval::val\fP[1]"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
