.TH "ost::DateNumber" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::DateNumber \- 
.PP
A number class that manipulates a string buffer that is also a date.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <numbers.h>\fP
.PP
Inherits \fBost::Number\fP, and \fBost::Date\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateNumber\fP (char *\fBbuffer\fP)"
.br
.ti -1c
.RI "virtual \fB~DateNumber\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A number class that manipulates a string buffer that is also a date. 

\fBAuthor:\fP
.RS 4
David Sugar <dyfet@ostel.com> a number that is also a date string. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ost::DateNumber::DateNumber (char * buffer)"
.SS "virtual ost::DateNumber::~DateNumber ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void ost::DateNumber::update (void)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBost::Date\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
