.TH "ost::ZNumber" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::ZNumber \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <numbers.h>\fP
.PP
Inherits \fBost::Number\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZNumber\fP (char *buf, unsigned \fBsize\fP)"
.br
.ti -1c
.RI "void \fBsetValue\fP (long value)"
.br
.ti -1c
.RI "long \fBoperator=\fP (long value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ost::ZNumber::ZNumber (char * buf, unsigned size)"
.SH "Member Function Documentation"
.PP 
.SS "long ost::ZNumber::operator= (long value)"
.PP
Reimplemented from \fBost::Number\fP.
.SS "void ost::ZNumber::setValue (long value)"
.PP
Reimplemented from \fBost::Number\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
