.TH "ost::SyncException" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::SyncException \- 
.PP
A sub-hierarchy for all task synchronizion related exceptions.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception.h>\fP
.PP
Inherits \fBost::ThrException\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyncException\fP (const \fBString\fP &what_arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A sub-hierarchy for all task synchronizion related exceptions. 

\fBAuthor:\fP
.RS 4
David Sugar <dyfet@ostel.com> Synchronization object exception hierarchy. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ost::SyncException::SyncException (const \fBString\fP & what_arg)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
