.TH "ost::ThreadQueue::_data" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ost::ThreadQueue::_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <buffer.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_data\fP * \fBnext\fP"
.br
.ti -1c
.RI "unsigned \fBlen\fP"
.br
.ti -1c
.RI "char \fBdata\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char \fBost::ThreadQueue::_data::data\fP[1]"
.SS "unsigned \fBost::ThreadQueue::_data::len\fP"
.SS "struct \fB_data\fP* \fBost::ThreadQueue::_data::next\fP\fC [read]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
