ost::Socket
NAME
ost::Socket -
The Socket is used as the base for all Internet protocol services under Common C++.
SYNOPSIS
#include <socket.h>
Inherited by ost::DCCPSocket, ost::SimpleTCPStream, ost::SocketPort, ost::TCPSocket [protected], ost::TCPStream, ost::TCPV6Socket [protected], ost::UDPSocket, ost::UnixSocket [protected], and ost::UnixStream.
Public Types
enum Family { IPV6 = AF_INET6, IPV4 = AF_INET }
enum Error { errSuccess = 0, errCreateFailed, errCopyFailed, errInput, errInputInterrupt, errResourceFailure, errOutput, errOutputInterrupt, errNotConnected, errConnectRefused, errConnectRejected, errConnectTimeout, errConnectFailed, errConnectInvalid, errConnectBusy, errConnectNoRoute, errBindingFailed, errBroadcastDenied, errRoutingDenied, errKeepaliveDenied, errServiceDenied, errServiceUnavailable, errMulticastDisabled, errTimeout, errNoDelay, errExtended, errLookupFail, errSearchErr, errInvalidValue }
enum Tos { tosLowDelay = 0, tosThroughput, tosReliability, tosMinCost, tosInvalid }
enum Pending { pendingInput, pendingOutput, pendingError }
typedef enum Family Family
typedef enum Error Error
typedef enum Tos Tos
typedef enum Pending Pending
Public Member Functions
virtual ~Socket ()
The socket base class may be 'thrown' as a result of an error, and the 'catcher' may then choose to destroy the object.
Socket & operator= (const Socket &from)
Sockets may also be duplicated by the assignment operator.
virtual IPV4Host getIPV4Sender (tpport_t *port=NULL) const
May be used to examine the origin of data waiting in the socket receive queue.
IPV4Host getSender (tpport_t *port=NULL) const
virtual IPV6Host getIPV6Sender (tpport_t *port=NULL) const
IPV4Host getIPV4Peer (tpport_t *port=NULL) const
Get the host address and port of the socket this socket is connected to.
IPV4Host getPeer (tpport_t *port=NULL) const
IPV6Host getIPV6Peer (tpport_t *port=NULL) const
IPV4Host getIPV4Local (tpport_t *port=NULL) const
Get the local address and port number this socket is currently bound to.
IPV4Host getLocal (tpport_t *port=NULL) const
IPV6Host getIPV6Local (tpport_t *port=NULL) const
IPV4Host getIPV4NAT (tpport_t *port=NULL) const
Perform NAT table lookup for this socket.
IPV4Host getNAT (tpport_t *port) const
IPV6Host getIPV6NAT (tpport_t *port=NULL) const
void setCompletion (bool immediate)
Used to specify blocking mode for the socket.
Error setLinger (bool linger)
Enable lingering sockets on close.
Error setKeepAlive (bool enable)
Set the keep-alive status of this socket and if keep-alive messages will be sent.
Error setTypeOfService (Tos service)
Set packet scheduling on platforms which support ip quality of service conventions.
bool isConnected (void) const
Can test to see if this socket is 'connected', and hence whether a 'catch' can safely call getPeer().
bool isActive (void) const
Test to see if the socket is at least operating or if it is mearly initialized.
bool operator! () const
Operator based testing to see if a socket is currently active.
bool isBroadcast (void) const
Return if broadcast has been enabled for the specified socket.
bool isRouted (void) const
Return if socket routing is enabled.
Error getErrorNumber (void) const
Often used by a 'catch' to fetch the last error of a thrown socket.
const char * getErrorString (void) const
Often used by a 'catch' to fetch the user set error string of a thrown socket, but only if EXTENDED error codes are used.
long getSystemError (void) const
const char * getSystemErrorString (void) const
virtual bool isPending (Pending pend, timeout_t timeout=TIMEOUT_INF)
Get the status of pending operations.
Static Public Member Functions
static bool check (Family fam)
See if a specific protocol family is available in the current runtime environment.
Protected Types
enum State { INITIAL, AVAILABLE, BOUND, CONNECTED, CONNECTING, STREAM }
typedef enum State State
Protected Member Functions
Error error (Error error, const char *err=NULL, long systemError=0) const
This service is used to throw all socket errors which usually occur during the socket constructor.
void error (const char *err) const
This service is used to throw application defined socket errors where the application specific error code is a string.
void setError (bool enable)
This service is used to turn the error handler on or off for 'throwing' exceptions by manipulating the thrown flag.
void endSocket (void)
Used as the default destructor for ending a socket.
Error connectError (void)
Used as a common handler for connection failure processing.
Error sendLimit (int limit=2048)
Set the send limit.
Error receiveLimit (int limit=1)
Set thr receive limit.
Error sendTimeout (timeout_t timer)
Set the send timeout for sending raw network data.
Error receiveTimeout (timeout_t timer)
Receive timeout for receiving raw network data.
Error sendBuffer (unsigned size)
Set the protocol stack network kernel send buffer size associated with the socket.
Error receiveBuffer (unsigned size)
Set the protocol stack network kernel receive buffer size associated with the socket.
Error bufferSize (unsigned size)
Set the total protocol stack network kernel buffer size for both send and receive together.
Error setBroadcast (bool enable)
Set the subnet broadcast flag for the socket.
Error setMulticastByFamily (bool enable, Family family=IPV4)
Setting multicast binds the multicast interface used for the socket to the interface the socket itself has been implicitly bound to.
Error setLoopbackByFamily (bool enable, Family family=IPV4)
Set the multicast loopback flag for the socket.
Error setTimeToLiveByFamily (unsigned char ttl, Family fam=IPV4)
Set the multicast time to live for a multicast socket.
Error join (const IPV4Multicast &ia)
Join a multicast group.
Error join (const IPV6Multicast &ia)
Error drop (const IPV4Multicast &ia)
Drop membership from a multicast group.
Error drop (const IPV6Multicast &ia)
Error setRouting (bool enable)
Set the socket routing to indicate if outgoing messages should bypass normal routing (set false).
Error setNoDelay (bool enable)
Enable/disable delaying packets (Nagle algorithm).
Socket (int domain, int type, int protocol=0)
An unconnected socket may be created directly on the local machine.
Socket (SOCKET fd)
A socket object may be created from a file descriptor when that descriptor was created either through a socket() or accept() call.
Socket ()
Create an inactive socket object for base constructors.
Socket (const Socket &source)
A socket can also be constructed from an already existing Socket object.
ssize_t readLine (char *buf, size_t len, timeout_t timeout=0)
Process a logical input line from a socket descriptor directly.
virtual ssize_t readData (void *buf, size_t len, char separator=0, timeout_t t=0)
Read in a block of len bytes with specific separator.
virtual ssize_t writeData (const void *buf, size_t len, timeout_t t=0)
Write a block of len bytes to socket.
Protected Attributes
struct {
   bool thrown: 1
   bool broadcast: 1
   bool route: 1
   bool keepalive: 1
   bool loopback: 1
   bool multicast: 1
   bool completion: 1
   bool linger: 1
   unsigned ttl: 8
} flags
SOCKET volatile so
the actual socket descriptor, in Windows, unlike posix it *cannot* be used as an file descriptor that way madness lies -- jfc
State volatile state
Static Protected Attributes
static Mutex mutex
Friends
SOCKET dupSocket (SOCKET s, Socket::State state)
Detailed Description
The Socket is used as the base for all Internet protocol services under Common C++.
A socket is a system resource (or winsock descriptor) that occupies a specific port address (and may be bound to a specific network interface) on the local machine. The socket may also be directly connected to a specific socket on a remote internet host.
This base class is not directly used, but is provided to offer properties common to other Common C++ socket classes, including the socket exception model and the ability to set socket properties such as QoS, 'sockopts' properties like Dont-Route and Keep-Alive, etc.
Author:
David Sugar <dyfet@ostel.com> base class of all sockets.
Examples:
tcpthread.cpp.
Member Typedef Documentation
typedef enum Error ost::Socket::Error
Reimplemented in ost::URLStream.
typedef enum Family ost::Socket::Family
typedef enum Pending ost::Socket::Pending
typedef enum State ost::Socket::State [protected]
typedef enum Tos ost::Socket::Tos
Member Enumeration Documentation
enum ost::Socket::Error
Enumerator:
errSuccess
errCreateFailed
errCopyFailed
errInput
errInputInterrupt
errResourceFailure
errOutput
errOutputInterrupt
errNotConnected
errConnectRefused
errConnectRejected
errConnectTimeout
errConnectFailed
errConnectInvalid
errConnectBusy
errConnectNoRoute
errBindingFailed
errBroadcastDenied
errRoutingDenied
errKeepaliveDenied
errServiceDenied
errServiceUnavailable
errMulticastDisabled
errTimeout
errNoDelay
errExtended
errLookupFail
errSearchErr
errInvalidValue
Reimplemented in ost::URLStream.
enum ost::Socket::Family
Enumerator:
IPV6
IPV4
enum ost::Socket::Pending
Enumerator:
pendingInput
pendingOutput
pendingError
enum ost::Socket::State [protected]
Enumerator:
INITIAL
AVAILABLE
BOUND
CONNECTED
CONNECTING
STREAM
enum ost::Socket::Tos
Enumerator:
tosLowDelay
tosThroughput
tosReliability
tosMinCost
tosInvalid
Constructor & Destructor Documentation
ost::Socket::Socket (int domain, int type, int protocol = 0) [protected]
An unconnected socket may be created directly on the local machine. Sockets can occupy both the internet domain (AF_INET) and UNIX socket domain (AF_UNIX) under unix. The socket type (SOCK_STREAM, SOCK_DGRAM) and protocol may also be specified. If the socket cannot be created, an exception is thrown.
Parameters:
domain socket domain to use.
type base type and protocol family of the socket.
protocol specific protocol to apply.
ost::Socket::Socket (SOCKET fd) [protected]
A socket object may be created from a file descriptor when that descriptor was created either through a socket() or accept() call. This constructor is mostly for internal use.
Parameters:
fd file descriptor of an already existing socket.
ost::Socket::Socket () [protected]
Create an inactive socket object for base constructors.
ost::Socket::Socket (const Socket & source) [protected]
A socket can also be constructed from an already existing Socket object. On POSIX systems, the socket file descriptor is dup()'d. On Win32, DuplicateHandle() is used.
Parameters:
source of existing socket to clone.
virtual ost::Socket::~Socket () [virtual]
The socket base class may be 'thrown' as a result of an error, and the 'catcher' may then choose to destroy the object. By assuring the socket base class is a virtual destructor, we can assure the full object is properly terminated.
Member Function Documentation
Error ost::Socket::bufferSize (unsigned size) [protected]
Set the total protocol stack network kernel buffer size for both send and receive together. Returns:
errSuccess on success
Parameters:
size of buffer.
static bool ost::Socket::check (Family fam) [static]
See if a specific protocol family is available in the current runtime environment. Returns:
true if family available.
Error ost::Socket::connectError (void) [protected]
Used as a common handler for connection failure processing. Returns:
correct failure code to apply.
Error ost::Socket::drop (const IPV6Multicast & ia) [protected]
Reimplemented in ost::UDPReceive.
Error ost::Socket::drop (const IPV4Multicast & ia) [protected]
Drop membership from a multicast group. Returns:
0 (errSuccess) on success, else error code.
Parameters:
ia address of multicast group to drop.
Reimplemented in ost::UDPReceive.
Referenced by ost::UDPReceive::drop().
void ost::Socket::endSocket (void) [protected]
Used as the default destructor for ending a socket. This will cleanly terminate the socket connection. It is provided for use in derived virtual destructors.
Referenced by ost::UDPReceive::endReceiver(), and ost::UDPTransmit::endTransmitter().
void ost::Socket::error (const char * err) const [inline, protected]
This service is used to throw application defined socket errors where the application specific error code is a string. Parameters:
err string or message to pass.
References error().
Referenced by error().
Error ost::Socket::error (Error error, const char * err = NULL, long systemError = 0) const [protected]
This service is used to throw all socket errors which usually occur during the socket constructor. Parameters:
error defined socket error id.
err string or message to pass.
systemError the system error# that caused the error
Error ost::Socket::getErrorNumber (void) const [inline]
Often used by a 'catch' to fetch the last error of a thrown socket. Returns:
error number of Error error.
Examples:
tcpthread.cpp.
const char* ost::Socket::getErrorString (void) const [inline]
Often used by a 'catch' to fetch the user set error string of a thrown socket, but only if EXTENDED error codes are used. Returns:
string for error message.
IPV4Host ost::Socket::getIPV4Local (tpport_t * port = NULL) const
Get the local address and port number this socket is currently bound to. Parameters:
port ptr to port number on local host.
Returns:
host address of interface this socket is bound to.
Referenced by ost::TCPSocket::getLocal().
IPV4Host ost::Socket::getIPV4NAT (tpport_t * port = NULL) const
Perform NAT table lookup for this socket. Used to allow an application to know the original ip:port pair the the client 'thinks' it is connecting to. Used mostly to transparently impersonate a remote server/service.
On error, 0.0.0.0:0 is returned and one of the following error codes is set: errServiceUnavailable - if nat is not supported on the current platform or if it was not compiled; errLookupFail - if the nat syscall failed for some reason (extended error code); errSearchErr - if the socket does not have nat information (i.e. is not nated).
NAT lookup is supported on NetFilter for ipv4 and ipv6 (Linux), IPFilter for ipv4 (Solaris, *BSD except OpenBSD, HP-UX, etc.) and Packet Filter for ipv4 and ipv6 (OpenBSD). When using IPFilter or Packet Filter, the first NAT lookup must be performed as root (the NAT device is read only for root and is opened once, unless an error occurs). Permissions on the nat device may be changed to solve this.
Warning:
When using IPFilter and Packet Filter, application data model must be the same as the running kernel (32/64 bits).
Parameters:
port ptr to NATed port number on local host.
Returns:
NATed host address that this socket is related to.
IPV4Host ost::Socket::getIPV4Peer (tpport_t * port = NULL) const
Get the host address and port of the socket this socket is connected to. If the socket is currently not in a connected state, then a host address of 0.0.0.0 is returned.
Parameters:
port ptr to port number of remote socket.
Returns:
host address of remote socket.
Reimplemented in ost::UDPSocket.
virtual IPV4Host ost::Socket::getIPV4Sender (tpport_t * port = NULL) const [virtual]
May be used to examine the origin of data waiting in the socket receive queue. This can tell a TCP server where pending 'connect' requests are coming from, or a UDP socket where it's next packet arrived from.
Parameters:
port ptr to port number of sender.
Returns:
host address, test with 'isInetAddress()'.
Reimplemented in ost::DCCPSocket.
Referenced by ost::TCPSocket::getRequest().
IPV6Host ost::Socket::getIPV6Local (tpport_t * port = NULL) const
Referenced by ost::TCPV6Socket::getLocal().
IPV6Host ost::Socket::getIPV6NAT (tpport_t * port = NULL) const
IPV6Host ost::Socket::getIPV6Peer (tpport_t * port = NULL) const
Reimplemented in ost::UDPSocket.
virtual IPV6Host ost::Socket::getIPV6Sender (tpport_t * port = NULL) const [virtual]
Reimplemented in ost::DCCPSocket.
Referenced by ost::TCPV6Socket::getRequest().
IPV4Host ost::Socket::getLocal (tpport_t * port = NULL) const [inline]
Reimplemented in ost::TCPSocket, and ost::TCPV6Socket.
IPV4Host ost::Socket::getNAT (tpport_t * port) const [inline]
IPV4Host ost::Socket::getPeer (tpport_t * port = NULL) const [inline]
Reimplemented in ost::UDPSocket.
Examples:
tcp.cpp, tcpservice.cpp, and tcpthread.cpp.
IPV4Host ost::Socket::getSender (tpport_t * port = NULL) const [inline]
long ost::Socket::getSystemError (void) const [inline]
const char* ost::Socket::getSystemErrorString (void) const
bool ost::Socket::isActive (void) const
Test to see if the socket is at least operating or if it is mearly initialized. 'initialized' sockets may be the result of failed constructors.
Returns:
true if not in initial state.
bool ost::Socket::isBroadcast (void) const [inline]
Return if broadcast has been enabled for the specified socket. Returns:
true if broadcast socket.
bool ost::Socket::isConnected (void) const
Can test to see if this socket is 'connected', and hence whether a 'catch' can safely call getPeer(). Of course, an unconnected socket will return a 0.0.0.0 address from getPeer() as well.
Returns:
true when socket is connected to a peer.
virtual bool ost::Socket::isPending (Pending pend, timeout_t timeout = TIMEOUT_INF) [virtual]
Get the status of pending operations. This can be used to examine if input or output is waiting, or if an error has occured on the descriptor.
Returns:
true if ready, false on timeout.
Parameters:
pend ready check to perform.
timeout in milliseconds, inf. if not specified.
Reimplemented in ost::TCPStream, ost::SimpleTCPStream, and ost::UnixStream.
Referenced by ost::UDPReceive::isInputReady(), ost::UDPTransmit::isOutputReady(), ost::UnixSocket::isPendingConnection(), ost::TCPV6Socket::isPendingConnection(), ost::TCPSocket::isPendingConnection(), ost::DCCPSocket::isPendingConnection(), and ost::UDPReceive::isPendingReceive().
bool ost::Socket::isRouted (void) const [inline]
Return if socket routing is enabled. Returns:
true if routing enabled.
Error ost::Socket::join (const IPV6Multicast & ia) [protected]
Reimplemented in ost::UDPReceive.
Error ost::Socket::join (const IPV4Multicast & ia) [protected]
Join a multicast group. Returns:
0 (errSuccess) on success, else error code.
Parameters:
ia address of multicast group to join.
Reimplemented in ost::UDPReceive.
Referenced by ost::UDPReceive::join().
bool ost::Socket::operator! () const
Operator based testing to see if a socket is currently active.
Reimplemented in ost::unixstream.
Socket& ost::Socket::operator= (const Socket & from)
Sockets may also be duplicated by the assignment operator.
virtual ssize_t ost::Socket::readData (void * buf, size_t len, char separator = 0, timeout_t t = 0) [protected, virtual]
Read in a block of len bytes with specific separator. Can be zero, or any other char. If \n or \r, it's treated just like a readLine(). Otherwise it looks for the separator.
Parameters:
buf pointer to byte allocation.
len maximum length to read.
separator separator for a particular ASCII character
t timeout for pending data in milliseconds.
Returns:
number of bytes actually read.
Reimplemented in ost::SSLStream.
ssize_t ost::Socket::readLine (char * buf, size_t len, timeout_t timeout = 0) [protected]
Process a logical input line from a socket descriptor directly. Parameters:
buf pointer to string.
len maximum length to read.
timeout for pending data in milliseconds.
Returns:
number of bytes actually read.
Reimplemented in ost::SSLStream.
Error ost::Socket::receiveBuffer (unsigned size) [protected]
Set the protocol stack network kernel receive buffer size associated with the socket. Returns:
errSuccess on success, or error.
Parameters:
size of buffer in bytes.
Error ost::Socket::receiveLimit (int limit = 1) [protected]
Set thr receive limit.
Error ost::Socket::receiveTimeout (timeout_t timer) [protected]
Receive timeout for receiving raw network data. Returns:
errSuccess if set.
Parameters:
timer value in milliseconds.
Error ost::Socket::sendBuffer (unsigned size) [protected]
Set the protocol stack network kernel send buffer size associated with the socket. Returns:
errSuccess on success, or error.
Parameters:
size of buffer in bytes.
Error ost::Socket::sendLimit (int limit = 2048) [protected]
Set the send limit.
Error ost::Socket::sendTimeout (timeout_t timer) [protected]
Set the send timeout for sending raw network data. Returns:
errSuccess if set.
Parameters:
timer value in millisec.
Error ost::Socket::setBroadcast (bool enable) [protected]
Set the subnet broadcast flag for the socket. This enables sending to a subnet and may require special image privileges depending on the operating system.
Returns:
0 (errSuccess) on success, else error code.
Parameters:
enable when set to true.
Reimplemented in ost::UDPTransmit.
Referenced by ost::UDPTransmit::setBroadcast().
void ost::Socket::setCompletion (bool immediate)
Used to specify blocking mode for the socket. A socket can be made non-blocking by setting setCompletion(false) or set to block on all access with setCompletion(true). I do not believe this form of non-blocking socket I/O is supported in winsock, though it provides an alternate asynchronous set of socket services.
Parameters:
immediate mode specify socket I/O call blocking mode.
Examples:
tcpservice.cpp.
void ost::Socket::setError (bool enable) [inline, protected]
This service is used to turn the error handler on or off for 'throwing' exceptions by manipulating the thrown flag. Parameters:
enable true to enable handler.
Error ost::Socket::setKeepAlive (bool enable)
Set the keep-alive status of this socket and if keep-alive messages will be sent. Returns:
0 on success.
Parameters:
enable keep alive messages.
Error ost::Socket::setLinger (bool linger)
Enable lingering sockets on close. Parameters:
linger specify linger enable.
Error ost::Socket::setLoopbackByFamily (bool enable, Family family = IPV4) [protected]
Set the multicast loopback flag for the socket. Loopback enables a socket to hear what it is sending.
Returns:
0 (errSuccess) on success, else error code.
Parameters:
enable when set to true.
family of protocol.
Referenced by ost::UDPSocket::setLoopback().
Error ost::Socket::setMulticastByFamily (bool enable, Family family = IPV4) [protected]
Setting multicast binds the multicast interface used for the socket to the interface the socket itself has been implicitly bound to. It is also used as a check flag to make sure multicast is enabled before multicast operations are used.
Returns:
0 (errSuccess) on success, else error code.
Parameters:
enable when set to true.
family of protocol.
Referenced by ost::UDPReceive::setMulticast(), ost::UDPTransmit::setMulticast(), and ost::UDPSocket::setMulticast().
Error ost::Socket::setNoDelay (bool enable) [protected]
Enable/disable delaying packets (Nagle algorithm). Returns:
0 on success.
Parameters:
enable disable Nagle algorithm when set to true.
Error ost::Socket::setRouting (bool enable) [protected]
Set the socket routing to indicate if outgoing messages should bypass normal routing (set false). Returns:
0 on success.
Parameters:
enable normal routing when set to true.
Reimplemented in ost::UDPTransmit, and ost::UDPReceive.
Referenced by ost::UDPReceive::setRouting(), and ost::UDPTransmit::setRouting().
Error ost::Socket::setTimeToLiveByFamily (unsigned char ttl, Family fam = IPV4) [protected]
Set the multicast time to live for a multicast socket. Returns:
0 (errSuccess) on success, else error code.
Parameters:
ttl time to live.
fam family of protocol.
Referenced by ost::UDPTransmit::setTimeToLive(), and ost::UDPSocket::setTimeToLive().
Error ost::Socket::setTypeOfService (Tos service)
Set packet scheduling on platforms which support ip quality of service conventions. This effects how packets in the queue are scheduled through the interface.
Returns:
0 on success, error code on failure.
Parameters:
service type of service enumerated type.
Reimplemented in ost::UDPTransmit.
Referenced by ost::UDPTransmit::setTypeOfService().
virtual ssize_t ost::Socket::writeData (const void * buf, size_t len, timeout_t t = 0) [protected, virtual]
Write a block of len bytes to socket. Parameters:
buf pointer to byte allocation.
len maximum length to write.
t timeout for pending data in milliseconds.
Returns:
number of bytes actually written.
Friends And Related Function Documentation
SOCKET dupSocket (SOCKET s, Socket::State state) [friend]
Member Data Documentation
bool ost::Socket::broadcast
bool ost::Socket::completion
struct { ... } ost::Socket::flags [protected]
bool ost::Socket::keepalive
bool ost::Socket::linger
bool ost::Socket::loopback
bool ost::Socket::multicast
Mutex ost::Socket::mutex [static, protected]
bool ost::Socket::route
SOCKET volatile ost::Socket::so [protected]
the actual socket descriptor, in Windows, unlike posix it *cannot* be used as an file descriptor that way madness lies -- jfc
State volatile ost::Socket::state [protected]
bool ost::Socket::thrown
unsigned ost::Socket::ttl
Author
Generated automatically by Doxygen for GNU CommonC++ from the source code.