.TH "oststring.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oststring.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBost::cistring_char_traits< charT >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string_char_traits< char > \fBost::cstring_char_traits\fP"
.br
.ti -1c
.RI "typedef std::basic_string< char > \fBost::cstring\fP"
.br
.ti -1c
.RI "typedef std::basic_string< char, cistring_char_traits< char > > \fBost::cistring\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
