.TH "pointer.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pointer.h \- 
.PP
Template for creating reference count managed smart pointers.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/missing.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::Pointer< T >\fP"
.br
.RI "\fIUsed to create and manage referece counted pointers. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Template for creating reference count managed smart pointers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
