.TH "process.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
process.h \- 
.PP
Process services.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/config.h>\fP
.br
\fC#include <cc++/thread.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::Process\fP"
.br
.RI "\fIA class for containing portable process related functions that help create portable code. \fP"
.ti -1c
.RI "class \fBost::Lockfile\fP"
.br
.RI "\fIThis class is used to create a 'named' lock entity that can be used to control access to a resource between multiple processes. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Process services. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
