.TH "socketport.h" 3 "2 May 2010" "GNU CommonC++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketport.h \- 
.PP
Network service framework and design pattern.  

.SH SYNOPSIS
.br
.PP
\fC#include <cc++/address.h>\fP
.br
\fC#include <cc++/socket.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBost::SocketPort\fP"
.br
.RI "\fIThe socket port is an internal class which is attached to and then serviced by a specific \fBSocketService\fP 'object'. \fP"
.ti -1c
.RI "class \fBost::SocketService\fP"
.br
.RI "\fIThe \fBSocketService\fP is a thread pool object that is meant to service attached socket ports. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Network service framework and design pattern. 


.SH "Author"
.PP 
Generated automatically by Doxygen for GNU CommonC++ from the source code.
